// Mocks generated by Mockito 5.4.6 from annotations
// in myapp/test/widgets/property_header_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:myapp/controllers/financial_controller.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FinancialController].
///
/// See the documentation for Mockito's code generation for more information.
class MockFinancialController extends _i1.Mock
    implements _i2.FinancialController {
  MockFinancialController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double get totalCost =>
      (super.noSuchMethod(Invocation.getter(#totalCost), returnValue: 0.0)
          as double);

  @override
  double get uplift =>
      (super.noSuchMethod(Invocation.getter(#uplift), returnValue: 0.0)
          as double);

  @override
  double get roi =>
      (super.noSuchMethod(Invocation.getter(#roi), returnValue: 0.0) as double);

  @override
  double get gdv =>
      (super.noSuchMethod(Invocation.getter(#gdv), returnValue: 0.0) as double);

  @override
  double get areaGrowth =>
      (super.noSuchMethod(Invocation.getter(#areaGrowth), returnValue: 0.0)
          as double);

  @override
  String get riskIndicator =>
      (super.noSuchMethod(
            Invocation.getter(#riskIndicator),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#riskIndicator),
            ),
          )
          as String);

  @override
  String get selectedScenario =>
      (super.noSuchMethod(
            Invocation.getter(#selectedScenario),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#selectedScenario),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void calculateFinancials(
    String? scenario,
    double? baseGdv,
    double? scenarioUplift,
  ) => super.noSuchMethod(
    Invocation.method(#calculateFinancials, [
      scenario,
      baseGdv,
      scenarioUplift,
    ]),
    returnValueForMissingStub: null,
  );

  @override
  void setCurrentPrice(double? price, double? gdv) => super.noSuchMethod(
    Invocation.method(#setCurrentPrice, [price, gdv]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
