// Mocks generated by Mockito 5.4.6 from annotations
// in myapp/test/widgets/uplift_analysis_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:myapp/controllers/gdv_controller.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GdvController].
///
/// See the documentation for Mockito's code generation for more information.
class MockGdvController extends _i1.Mock implements _i2.GdvController {
  MockGdvController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double get gdvSold =>
      (super.noSuchMethod(Invocation.getter(#gdvSold), returnValue: 0.0)
          as double);

  @override
  double get gdvOnMarket =>
      (super.noSuchMethod(Invocation.getter(#gdvOnMarket), returnValue: 0.0)
          as double);

  @override
  double get gdvArea =>
      (super.noSuchMethod(Invocation.getter(#gdvArea), returnValue: 0.0)
          as double);

  @override
  double get weightSold =>
      (super.noSuchMethod(Invocation.getter(#weightSold), returnValue: 0.0)
          as double);

  @override
  double get weightOnMarket =>
      (super.noSuchMethod(Invocation.getter(#weightOnMarket), returnValue: 0.0)
          as double);

  @override
  double get weightArea =>
      (super.noSuchMethod(Invocation.getter(#weightArea), returnValue: 0.0)
          as double);

  @override
  double get finalGdv =>
      (super.noSuchMethod(Invocation.getter(#finalGdv), returnValue: 0.0)
          as double);

  @override
  double get cautiousGdv =>
      (super.noSuchMethod(Invocation.getter(#cautiousGdv), returnValue: 0.0)
          as double);

  @override
  double get baseGdv =>
      (super.noSuchMethod(Invocation.getter(#baseGdv), returnValue: 0.0)
          as double);

  @override
  double get optimisticGdv =>
      (super.noSuchMethod(Invocation.getter(#optimisticGdv), returnValue: 0.0)
          as double);

  @override
  Map<String, _i2.UpliftData> get scenarioUplifts =>
      (super.noSuchMethod(
            Invocation.getter(#scenarioUplifts),
            returnValue: <String, _i2.UpliftData>{},
          )
          as Map<String, _i2.UpliftData>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void calculateFinalGdv() => super.noSuchMethod(
    Invocation.method(#calculateFinalGdv, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> calculateGdv({
    required String? postcode,
    required int? habitableRooms,
    required double? totalFloorArea,
    required double? currentPrice,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#calculateGdv, [], {
              #postcode: postcode,
              #habitableRooms: habitableRooms,
              #totalFloorArea: totalFloorArea,
              #currentPrice: currentPrice,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void updateGdvSources({double? sold, double? onMarket, double? area}) =>
      super.noSuchMethod(
        Invocation.method(#updateGdvSources, [], {
          #sold: sold,
          #onMarket: onMarket,
          #area: area,
        }),
        returnValueForMissingStub: null,
      );

  @override
  void updateUpliftRates({
    required double? currentPrice,
    required double? totalFloorArea,
  }) => super.noSuchMethod(
    Invocation.method(#updateUpliftRates, [], {
      #currentPrice: currentPrice,
      #totalFloorArea: totalFloorArea,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void calculateAllScenarioUplifts() => super.noSuchMethod(
    Invocation.method(#calculateAllScenarioUplifts, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
