// Mocks generated by Mockito 5.4.6 from annotations
// in myapp/test/services/cloudinary_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cloudinary_public/cloudinary_public.dart' as _i2;
import 'package:dio/dio.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCloudinaryImage_0 extends _i1.SmartFake
    implements _i2.CloudinaryImage {
  _FakeCloudinaryImage_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCloudinaryResponse_1 extends _i1.SmartFake
    implements _i2.CloudinaryResponse {
  _FakeCloudinaryResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CloudinaryPublic].
///
/// See the documentation for Mockito's code generation for more information.
class MockCloudinaryPublic extends _i1.Mock implements _i2.CloudinaryPublic {
  MockCloudinaryPublic() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get cache =>
      (super.noSuchMethod(Invocation.getter(#cache), returnValue: false)
          as bool);

  @override
  _i2.CloudinaryImage getImage(String? publicId) =>
      (super.noSuchMethod(
            Invocation.method(#getImage, [publicId]),
            returnValue: _FakeCloudinaryImage_0(
              this,
              Invocation.method(#getImage, [publicId]),
            ),
          )
          as _i2.CloudinaryImage);

  @override
  _i3.Future<List<_i2.CloudinaryResponse>> uploadFiles(
    List<_i2.CloudinaryFile>? files, {
    String? uploadPreset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadFiles,
              [files],
              {#uploadPreset: uploadPreset},
            ),
            returnValue: _i3.Future<List<_i2.CloudinaryResponse>>.value(
              <_i2.CloudinaryResponse>[],
            ),
          )
          as _i3.Future<List<_i2.CloudinaryResponse>>);

  @override
  _i3.Future<_i2.CloudinaryResponse> uploadFile(
    _i2.CloudinaryFile? file, {
    String? uploadPreset,
    _i4.ProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadFile,
              [file],
              {#uploadPreset: uploadPreset, #onProgress: onProgress},
            ),
            returnValue: _i3.Future<_i2.CloudinaryResponse>.value(
              _FakeCloudinaryResponse_1(
                this,
                Invocation.method(
                  #uploadFile,
                  [file],
                  {#uploadPreset: uploadPreset, #onProgress: onProgress},
                ),
              ),
            ),
          )
          as _i3.Future<_i2.CloudinaryResponse>);

  @override
  _i3.Future<_i2.CloudinaryResponse> uploadFutureFile(
    _i3.Future<_i2.CloudinaryFile>? file, {
    String? uploadPreset,
    _i4.ProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadFutureFile,
              [file],
              {#uploadPreset: uploadPreset, #onProgress: onProgress},
            ),
            returnValue: _i3.Future<_i2.CloudinaryResponse>.value(
              _FakeCloudinaryResponse_1(
                this,
                Invocation.method(
                  #uploadFutureFile,
                  [file],
                  {#uploadPreset: uploadPreset, #onProgress: onProgress},
                ),
              ),
            ),
          )
          as _i3.Future<_i2.CloudinaryResponse>);

  @override
  _i3.Future<List<_i2.CloudinaryResponse>> multiUpload(
    List<_i3.Future<_i2.CloudinaryFile>>? files, {
    String? uploadPreset,
    _i4.ProgressCallback? onProgress,
    void Function(int)? currentUploadIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #multiUpload,
              [files],
              {
                #uploadPreset: uploadPreset,
                #onProgress: onProgress,
                #currentUploadIndex: currentUploadIndex,
              },
            ),
            returnValue: _i3.Future<List<_i2.CloudinaryResponse>>.value(
              <_i2.CloudinaryResponse>[],
            ),
          )
          as _i3.Future<List<_i2.CloudinaryResponse>>);

  @override
  _i3.Future<_i2.CloudinaryResponse?> uploadFileInChunks(
    _i2.CloudinaryFile? file, {
    String? uploadPreset,
    _i4.ProgressCallback? onProgress,
    int? chunkSize = 20000000,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadFileInChunks,
              [file],
              {
                #uploadPreset: uploadPreset,
                #onProgress: onProgress,
                #chunkSize: chunkSize,
              },
            ),
            returnValue: _i3.Future<_i2.CloudinaryResponse?>.value(),
          )
          as _i3.Future<_i2.CloudinaryResponse?>);
}
